<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hulk Technologies International — Technology on Demand</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400;12..96,600;12..96,800&family=Hanken+Grotesk:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="styles.css">
</head>
<body>

<header>
  <div class="wrap">

    <!-- Top bar: greeting + sign out -->
    <div class="header-bar fade d1">
      <!-- 👇 auth.js writes the user's name into .greet span -->
      <div class="greet">Welcome back, <span>there</span> — your fleet is ready to deploy.</div>
      <button class="signout-btn" onclick="signOut()">Sign out</button>
    </div>

    <h1 class="fade d2">Technology, <span class="em">on demand.</span></h1>
    <p class="sub fade d3">Request, reserve, and manage enterprise technology resources through a secure, scalable, serverless cloud platform. Local logistics — global reach.</p>

  </div> <!-- /.wrap — FIX: this was missing, causing layout breakage -->
</header>

<section id="catalog">
  <div class="wrap">
    <div id="catalogGrid">
      <div class="sec-head">
        <span class="kicker">Technology &amp; IT Equipment</span>
        <h2>Choose a category</h2>
        <p>Click any category to browse available models and reserve.</p>
      </div>
      <div class="grid">

        <div class="card fade d1">
          <h3>Laptops</h3>
          <p class="desc">Portable workstations for hybrid teams, events, and short-term deployments.</p>
          <button class="view-btn" onclick="openCategory('laptops')">View list &rarr;</button>
        </div>

        <div class="card fade d2">
          <h3>Desktop Workstations</h3>
          <p class="desc">High-performance towers for engineering, design, and compute-heavy work.</p>
          <button class="view-btn" onclick="openCategory('desktops')">View list &rarr;</button>
        </div>

        <div class="card fade d3">
          <h3>Monitors</h3>
          <p class="desc">4K and ultrawide displays to extend any workspace at a moment's notice.</p>
          <button class="view-btn" onclick="openCategory('monitors')">View list &rarr;</button>
        </div>

        <div class="card fade d4">
          <h3>Network Switches</h3>
          <p class="desc">Managed switching to stand up secure, high-throughput infrastructure fast.</p>
          <button class="view-btn" onclick="openCategory('switches')">View list &rarr;</button>
        </div>

        <div class="card fade d5">
          <h3>AV Equipment</h3>
          <p class="desc">Projectors, speakers, and conferencing kits for events and boardrooms.</p>
          <button class="view-btn" onclick="openCategory('av')">View list &rarr;</button>
        </div>

      </div>
    </div>

    <div id="listView">
      <button class="back" onclick="showCategories()">&larr; BACK TO CATEGORIES</button>
      <h2 class="list-title" id="listTitle"></h2>
      <p class="list-meta" id="listMeta"></p>
      <div class="rows" id="rows"></div>
    </div>
  </div>
</section>

<section id="mission" style="padding-top:20px">
  <div class="wrap">
    <div class="mission">
      <span class="kicker">Our Mission</span>
      <blockquote>Technology on demand — turning a local business into a <em>global service provider.</em></blockquote>
      <p class="full">Hulk Technologies International is a cloud-native technology equipment rental platform that enables businesses to request, reserve, and manage technology resources through a secure, scalable, serverless AWS infrastructure. Our mission is to provide technology on demand while leveraging cloud computing to transform a local business into a global service provider.</p>
    </div>
  </div>
</section>

<footer>
  <div class="wrap foot-in">
    <a class="brand" href="#"><span class="mark">H</span>
      <span><b>HULK TECHNOLOGIES</b><span class="intl">INTERNATIONAL</span></span></a>
    <div class="badges">
      <span class="badge">SECURE</span><span class="badge">SCALABLE</span>
      <span class="badge">SERVERLESS</span><span class="badge">CLOUD-NATIVE</span>
    </div>
    <p class="copy">© 2026 Hulk Technologies International — Technology on demand, anywhere.</p>
  </div>
</footer>

<!--
  SCRIPT LOAD ORDER — do not change:
  1. config.js   → sets window.APP_CONFIG (generated by amplify.yml at build time)
  2. auth.js     → reads APP_CONFIG, handles Cognito login/token exchange, exposes signOut()
  3. script.js   → reads APP_CONFIG for API URLs, calls openCategory() / reserve()
-->
<script src="config.js"></script>
<script src="auth.js"></script>
<script src="script.js"></script>

</body>
</html>
