/**
 * generate-config.js
 * Runs during the Amplify build phase: node generate-config.js
 * Reads environment variables set in the Amplify console and writes config.js.
 * Never commit config.js — it is gitignored and generated fresh on every deploy.
 */

const fs = require('fs');

// ─── Required environment variables ──────────────────────────────────────────
const REQUIRED = [
  'COGNITO_DOMAIN',
  'CLIENT_ID',
  'REDIRECT_URI',
  'LIST_EQUIPMENT_URL',
  'RESERVE_URL'
];

let missing = false;
for (const key of REQUIRED) {
  if (!process.env[key]) {
    console.error(`ERROR: Environment variable "${key}" is not set.`);
    console.error(`       Go to Amplify console → your app → Hosting → Environment variables.`);
    missing = true;
  }
}
if (missing) process.exit(1);

// ─── Write config.js ─────────────────────────────────────────────────────────
const config = `// Auto-generated by generate-config.js during Amplify build. Do not edit.
window.APP_CONFIG = {
  cognitoDomain:    "${process.env.COGNITO_DOMAIN}",
  clientId:         "${process.env.CLIENT_ID}",
  redirectUri:      "${process.env.REDIRECT_URI}",
  listEquipmentUrl: "${process.env.LIST_EQUIPMENT_URL}",
  reserveUrl:       "${process.env.RESERVE_URL}"
};
`;

fs.writeFileSync('config.js', config, 'utf8');

console.log('config.js generated successfully:');
console.log(config);
